gui:
  sidePanelWidth: 0.25
  mouseEvents: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    verbose: always
keybinding:
  universal:
    quit: 'Q'
    return: 'q'
customCommands:
  - key: 'F'
    context: 'localBranches'
    command: 'git checkout -b {{.SelectedLocalBranch.Name}}-fork'
    description: 'Create fork branch from selected'
  - key: 'B'
    context: 'localBranches'
    command: 'branch={{.SelectedLocalBranch.Name}}; git checkout ${branch%-fork}'
    description: 'Return to original branch (strip -fork suffix)'
  - key: 'S'
    context: 'localBranches'
    command: 'zsh -ic switch_to_tmp_branch'
    description: 'Switch to personal tmp branch and rebase'
  - key: 'D'
    context: 'localBranches'
    prompts:
      - type: 'confirm'
        title: 'Delete branch'
        body: 'Switch to tmp branch and delete {{.SelectedLocalBranch.Name}} ?'
    command: 'zsh -ic switch_to_tmp_branch && git branch -D {{.SelectedLocalBranch.Name}}'
    description: 'Switch to tmp branch and delete selected branch'
